let variable = true;
console.log(variable);
console.log(typeof variable);
variable = Number(variable);
console.log(variable);
console.log(typeof variable);
variable = variable.toString();
console.log(variable);
console.log(typeof variable);
variable = Boolean(variable);
console.log(variable);
console.log(typeof variable);
